---
version: 3

images:
  base_image:
    name: 192.168.124.24/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy: requirements.yml

additional_build_files:
  - src: ansible.cfg
    dest: ./

additional_build_steps:
  prepend_base:
    - COPY _build/ansible.cfg /etc/ansible/ansible.cfg
