---
- name: Create content
  hosts: all
  become: true
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory
    - name: Create file inside directory
      ansible.builtin.file:
        path: "{{DIRECTORY}}/{{FILE}}"
        state: touch
    - name: Add content to file
      ansible.builtin.copu:
        dest: "{{DIRECTORY}}/{{FILE}}"
        content: "{{CONTENT}}"
