---
- name: Master Playbook
  hosts: all
  become: true
  tasks:
    - name: Create Directory
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory
    - name: Create file
      ansible.builtin.file:
        path: "{{DIRECTORY}}/{{FILE}}"
        state: touch
    - name: Add content
      ansible.builtin.copy:
        dest: "{{DIRECTORY}}/{{FILE}}"
        content: "{{CONTENT}}"
