---
- hosts: all
  name: Create file and directory
  become: true
  tasks:
    - name: Create Directory
      ansible.builtin.file:
        dest: "{{ DIRECTORY }}"
        state: directory

    - name: Create file
      ansible.builtin.file:
         dest: "{{ DIRECTORY }}/{{ FILE }}"
         state: touch

    - name: Add Content to file
      ansible.builtin.copy:
        dest: "{{DIRECTORY}}/{{FILE}}"
        content: "{{CONTENT}}"
        create: true
