---
version: 3

images:
  base_image:
    name: 192.168.124.24/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python: requirements.txt
  system: bindep.txt
