---
- name: Read user data from users.conf
  ansible.builtin.include_vars:
    file: users.yml

- name: Create users based on user_list
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups | default('users') }}"
  loop: "{{ users }}"
